server:
  port: 9280

# Spring Configuration
spring:
  cloud:
    config:
      enabled: false

# Logging
logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    org.springframework.cloud: INFO
    org.springframework.cloud.sleuth: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: INFO
    com.qiagen: DEBUG

# Discovery Server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9061/eureka}