### This is the main way to configure the application (other than annotations).
### This file is in Yaml format.
### https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties


### This is the main way to configure the application (other than annotations).
### This file is in Yaml format.
### https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties


server:
  port: 9180

# Spring Configuration
spring:
  cloud:
    config:
      enabled: false
  datasource:
    password: Adidas447.
    url: jdbc:mysql://adidas-db:3306/adidas?useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL57Dialect


# Logging
logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    org.springframework.cloud: INFO
    org.springframework.cloud.sleuth: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: INFO
    com.qiagen: DEBUG

# Discovery Server
eureka:
  instance:
    prefer-ip-address: true # Register the IP of the service rather than the server name
  client:
    register-with-eureka: true
    fetch-registry: false # Pull down a local copy of the registry
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://naming-server:9061/eureka}
